name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          cache: true

      - name: Build APK
        run: |
          sed -i '/flutter_lints/d' example/pubspec.yaml || true
          sed -i '/flutter_lints/d' pubspec.yaml || true
          rm -f example/analysis_options.yaml analysis_options.yaml || true
          rm -f example/pubspec.lock pubspec.lock || true
          cd example
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: live-streaming-app
          path: example/build/app/outputs/flutter-apk/app-release.apk
